version: '2'
services:
  api_gateway:
    build: ./api_gateway
    image: smart-chat/api_gateway
    container_name: smart-chat-api-gateway
    ports:
        - "3030:3000"
    environment:
      PORT: 3000

  users:
    build: ./users
    image: smart-chat/users
    container_name: smart-chat-users
    depends_on:
      - mongo
    links:
      - mongo
    ports:
        - "5554:8080"

  channels:
    build: ./channels
    image: smart-chat/channels
    container_name: smart-chat-channels
    ports:
      - "6464:6465"
    depends_on:
      - postgres
    environment:
      APP_DB_USERNAME: "root"
      APP_DB_PASSWORD: "root"
      APP_DB_NAME: "channels"

  web:
    build: ./web
    image: smart-chat/web
    container_name: smart-chat-web
    depends_on:
      - api_gateway
    links:
      - api_gateway
    ports:
      - "5000:5000"
    environment:
      VIRTUAL_HOST: web.local

  mongo:
    command: mongod
    image: mongo:3.4
    container_name: smart-chat-mongodb
    ports:
      - "27100:27017" # map port to none standard port to avoid conflicts
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    logging:
      driver: none

  postgres:
    image: postgres
    container_name: smart-chat-postgresql
    restart: always
    ports:
      - "8001:5432"

  redis:
    image: redis:4.0.2
    container_name: smart-chat-redis
    ports:
        - "6379"
